replicaCount: 1

image:
  repository: cranecloud/monitoring-api
  pullPolicy: Always
  tag: ${{ DOCKER_IMAGE_TAG }}

nameOverride: "monitoring-api"
fullnameOverride: ""


environment:
  DATABASE_URI: ${{ DATABASE_URL }}
  DATABASE_USER: ${{ DATABASE_USER }}
  TEST_DATABASE_URI: ${{ TEST_DATABASE_URL }}
  FLASK_APP: server.py
  FLASK_APP_SALT: ${{ APP_SALT }}
  FLASK_APP_SECRET: ${{ APP_SECRET }}
  FLASK_ENV: production
  LOGGER_APP_URL: ${{ LOGGER_APP_URL }}
  PRODUCT_BASE_URL: ${{PRODUCT_BASE_URL}}
