replicaCount: 1

image:
  repository: gcr.io/crane-cloud-274413/monitoring-api
  pullPolicy: Always
  tag: ${{ DOCKER_IMAGE_TAG }}

nameOverride: "monitoring-api"

nginxConf:
  server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://localhost:5000/;
            proxy_set_header Host "localhost";
        }
    }

service:
  type: NodePort
  port: 80

environment:
  DATABASE_URI: ${{ DATABASE_URL }}
  DATABASE_USER: ${{ DATABASE_USER }}
  TEST_DATABASE_URI: ${{ TEST_DATABASE_URL }}
  FLASK_APP: server.py
  FLASK_APP_SALT: ${{ FLASK_APP_SALT }}
  FLASK_APP_SECRET: ${{ FLASK_APP_SECRET }}
  FLASK_ENV: production
  LOGGER_APP_URL: ${{ LOGGER_APP_URL }}
  PRODUCT_BASE_URL: ${{PRODUCT_BASE_URL}}

celery:
  create: false

redis:
  create: false